### ISSUE TITLE
首次使用发现的一些问题

### ISSUE THREAD

**Issue by Jetereting** [suyuan32/simple-admin-example-api-single#1]
1. 编写好 ent/schma/xx.go 后，如果里面还有类似 SortMixin、StatusMixin ，执行 make gen-ent 不生成对应的字段
2. 执行 make gen-api-ent-logic model=xx group=xx 后 在logic/xx/xxlist_logic.go 文件 v.ID 类型不匹配，v.CreatedAt 和 v.UpdateAt 不存在
3. 按照流程图这时候需要检查 desc 文件中搜索参数，不合适的话修改 proto 文件，但是 proto 文件不存在
4. desc 文件中没有 sort, status 字段

**Comment by suyuan32** [comment]
代码生成必须有 base id mixin 或者 base uuid mixin，否则需要自己写

**Comment by Jetereting** [comment]
> 代码生成必须有 base id mixin 或者 base uuid mixin，否则需要自己写

可以在 ent/schema/example.go 中示例下吗？不知道应该怎么加这3项

**Comment by suyuan32** [comment]
https://github.com/suyuan32/simple-admin-core/blob/master/rpc/ent/schema/department.go

**Comment by suyuan32** [comment]
https://www.bilibili.com/video/BV1oa4y1A7rT/

**Comment by Jetereting** [comment]
他生效了，谢谢！上面的问题基本都没有了，本项目README 中好像缺了一步： make gen-api

**Comment by suyuan32** [comment]
是的，加上去了
