### ISSUE TITLE
执行 make gen-api 时报错

### ISSUE THREAD

**Issue by Jetereting** [suyuan32/simple-admin-example-api-single#3]
测试项目地址：https://github.com/Jetereting/student
```bash
➜  school git:(master) ✗ make gen-api                                      
goctls api go --api ./desc/all.api --dir ./ --trans_err=true --style=go_zero
Generating...
Error: desc/student.api line 15:8 can not found declaration 'Name' in context
```

**Comment by Jetereting** [comment]
明确复现了 当类型中有 json ,对应 ent 的 field.Strings , 则 make gen-api 时就会报错

**Comment by Jetereting** [comment]
我运行后发现没有自动生成 b_student 表，是漏了哪一步

**Comment by suyuan32** [comment]
![try](https://github.com/suyuan32/simple-admin-example-api-single/assets/21239039/d01242f3-4962-4929-b05d-682cdf5b7929)
这么多问题来星球问吧

**Comment by Jetereting** [comment]
> ![try](https://user-images.githubusercontent.com/21239039/242535848-d01242f3-4962-4929-b05d-682cdf5b7929.jpg) 这么多问题来星球问吧

星球地址来一下

**Comment by suyuan32** [comment]
扫码即可加入了，现在有活动可以免费进入

**Comment by suyuan32** [comment]
项目地址：https://doc.ryansu.pro/zh/
待添加的功能： https://github.com/users/suyuan32/projects/1/views/1
推荐开发模块方向：https://github.com/users/suyuan32/projects/5/views/1

现招募第一批体验用户，由于星球刚成立，内容还不太多，我们将提供一批免费用户名额(约30-50人)。 
如何获得资格？ 
1. 使用 Simple Admin 开发的模块且 star 大于 20 的开源项目的所有者 
2. 使用 Simple Admin 开发的模块， 文档详细且内容丰富的开源项目所有者 
3. 为 Simple Admin 任意项目贡献代码行数大于 100 的开发者 
4. 在各个渠道推荐 Simple Admin 的积极用户，邀请进群5人以上即可 

为什么要创建知识星球？ 
1. 新用户重复提问，重复问题没有时间回答 
2. 知识星球提供一个大家分享自己开发的模块的平台，可以帮助大家快速获得 star 
3. 管理员时间也很宝贵，项目的文档和视频已经很详细了，没有太多时间为新手提供回答，特别是重复的回答 
4. 提供额外的学习文档和视频，方便新手快速学会微服务架构 
5. 免费的项目是不可持续的，为爱发电迟早会放弃 

知识星球内的提问管理员会尽量回答，有需求的可以加入，qq群和微信群仍会正常运行，但是重复的或者文档有的问题不再回复
